formatter: "markdown table" # this is required
version: "0.16"

header-from: "main.tf"
footer-from: ""

sections:
  hide:
    - providers

content: |-
  {{ .Header }}
  ## Example

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  {{ .Requirements }}

  ## Usage
  Basic usage of this module is as follows:

  ```hcl
  module "example" {
    {{"\t"}} source  = "github.com/iganosaigo/terraform-yandex-compute-instance.git"
    {{- if .Module.RequiredInputs }}
    {{"\n\t"}} # Required variables
    {{- range .Module.RequiredInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue }}
    {{- end }}
    {{- end }}
    {{- if .Module.OptionalInputs }}
    {{"\n\t"}} # Optional variables
    {{- range .Module.OptionalInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
    {{- end }}
    {{- end }}
  }
  ```
  {{ .Providers }}
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_TF_DOCS -->
      {{ .Content }}
      <!-- END_TF_DOCS -->
output-values:
  enabled: false
  from: ""
recursive:
  enabled: false
  path: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
